version: '3.8'

services:
  # Removemos o serviço postgres local, pois vamos usar o Render
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vendas-postes-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d1bg2895pdvs73dsavg0-a:5432/ativaposte
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: aa303O04NteXaSLTrM0uOQ14Q2VnRKIw
      SPRING_PROFILES_ACTIVE: production
    ports:
      - "8080:8080"
    networks:
      - vendas-network

networks:
  vendas-network:
    driver: bridge