services:
  - type: web
    name: vendas-postes-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d1bg2895pdvs73dsavg0-a:5432/ativaposte
      - key: SPRING_DATASOURCE_USERNAME
        value: admin
      - key: SPRING_DATASOURCE_PASSWORD
        value: aa303O04NteXaSLTrM0uOQ14Q2VnRKIw
      - key: SPRING_DATASOURCE_DRIVER
        value: org.postgresql.Driver
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: validate
      - key: SPRING_JPA_SHOW_SQL
        value: false
      - key: JAVA_OPTS
        value: "-Xmx512m -Xms256m -Dfile.encoding=UTF-8"
      - key: LANG
        value: en_US.UTF-8
      - key: LC_ALL
        value: en_US.UTF-8